"""Add year column to all film tables

Revision ID: f2d728fea72d
Revises: c6bd2f5c9b3f
Create Date: 2024-11-29 18:13:16.552328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d728fea72d'
down_revision: Union[str, None] = 'c6bd2f5c9b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historic', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('horror', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('thriller', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thriller', 'year')
    op.drop_column('horror', 'year')
    op.drop_column('historic', 'year')
    # ### end Alembic commands ###
